title: Maria Isabel Lopez # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Maria I'm a Computer Science Student.  
  <br><br>
  I do things online. 
  <br><br>
  <a href="https://linkedin.com/in/mi-lopez ">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-164761622-1 # your Google Analytics tracking ID here
