title: Maria Isabel Lopez # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Maria I'm a Computer Science Student in Lima, Peru. I work as a Freelancer at <a href="https://www.upwork.com/freelancers/~01b0ef99178843ede6">Upwork</a> and <a href="https://www.workana.com/freelancer/a7d9332d18d878c19f01c518e58673f0">Workana</a> 
  mostly as a Zoho Developer but my interest range from different areas of software development.
  <br><br>
  I'm mostly pursuing opportunities in Web development and Front-End experiences but as my higher education continues I would
  like to pursue a career in Data Science and continue to get a Master and Phd in Statistic and Computer Science.  
  <br><br>
  <a href="https://linkedin.com/in/mi-lopez ">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-164761622-1 # your Google Analytics tracking ID here
